[package]
name = "path_tracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19.3"
nalgebra = "0.29.0"
rand = "0.8.4"
image = "0.23.14"
ocl-include = "0.5.1"
uni-path = "1.51.1"